/*
UN CONDICIONAL NOS SIRVE PARA CONTROLAR EL 
FLUJO DEL PROGRAMA. ES UNA ESTRUCTURA DE CONTROL
NOS PERMITE TOMAR DECISIONES TENIENDO EN CUENTA
VALORES DE VARIABLES, CONSTANTES ETC.
EXIETN CONDICIONALES SENCILLOS(O SIMPLES) Y CONDICIONALES DOBLES(O COMPUESTO)
*/
//CONDICIONAL SENCILLO
//P.E CREAR UN PROGRAMA QUE PIDA AL EDAD DE UN USUARIO Y MUESTRE CUANDO ESTE SEA MAYOR DE EDAD
let edad = parseInt(prompt("Ingrese edad"));
let mayorEdad = edad >= 18;
//si la persona es mayor de edad...
if (mayorEdad){
    console.log("Ud es mayor de edad");
}